# Generated by Django 5.0 on 2025-08-12 10:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaveArchiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField(verbose_name='forecast_time')),
                ('tp', models.FloatField(help_text='from tab01', verbose_name='Tp')),
                ('hs', models.FloatField(help_text='from tab41/ Unit(m)', verbose_name='Hs')),
                ('hmax', models.FloatField(help_text='Hs * 1.8/ Unit(m)', verbose_name='Hmax')),
                ('tz', models.FloatField(help_text='Tr from tab41', verbose_name='Tz')),
                ('wave_direction_41', models.FloatField(help_text='from tab41', verbose_name='wave_direction')),
            ],
        ),
        migrations.CreateModel(
            name='WaveForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField(verbose_name='forecast_time')),
                ('tp', models.FloatField(help_text='from tab01', verbose_name='Tp')),
                ('hs', models.FloatField(help_text='from tab41/ Unit(m)', verbose_name='Hs')),
                ('hmax', models.FloatField(help_text='Hs * 1.8/ Unit(m)', verbose_name='Hmax')),
                ('tz', models.FloatField(help_text='Tr from tab41', verbose_name='Tz')),
                ('wave_direction_41', models.FloatField(help_text='from tab41', verbose_name='wave_direction')),
            ],
        ),
        migrations.CreateModel(
            name='WaveStationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='location')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'wave station',
                'verbose_name_plural': 'wave stations',
                'indexes': [models.Index(fields=['location'], name='wave_location_gist_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='wavestationmodel',
            constraint=models.UniqueConstraint(fields=('location',), name='unique_wave_location'),
        ),
        migrations.AddField(
            model_name='waveforecastmodel',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='waveforecastapp.wavestationmodel', verbose_name='station'),
        ),
        migrations.AddField(
            model_name='wavearchivemodel',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='waveforecastapp.wavestationmodel', verbose_name='station'),
        ),
        migrations.AddIndex(
            model_name='waveforecastmodel',
            index=models.Index(fields=['forecast_time', 'station'], name='waveforecas_forecas_e8e663_idx'),
        ),
        migrations.AddIndex(
            model_name='waveforecastmodel',
            index=models.Index(fields=['station'], name='waveforecas_station_d54fde_idx'),
        ),
        migrations.AddIndex(
            model_name='waveforecastmodel',
            index=models.Index(fields=['forecast_time'], name='waveforecas_forecas_ce5196_idx'),
        ),
        migrations.AddIndex(
            model_name='wavearchivemodel',
            index=models.Index(fields=['forecast_time', 'station'], name='waveforecas_forecas_eb1378_idx'),
        ),
        migrations.AddIndex(
            model_name='wavearchivemodel',
            index=models.Index(fields=['station'], name='waveforecas_station_952b11_idx'),
        ),
        migrations.AddIndex(
            model_name='wavearchivemodel',
            index=models.Index(fields=['forecast_time'], name='waveforecas_forecas_195a78_idx'),
        ),
    ]
