# Generated by Django 5.0 on 2025-08-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waveforecastapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waveforecastmodel',
            old_name='wave_direction_41',
            new_name='wave_direction',
        ),
    ]
