# Generated by Django 5.0 on 2025-08-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waveforecastapp', '0002_rename_wave_direction_41_waveforecastmodel_wave_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wavearchivemodel',
            old_name='wave_direction_41',
            new_name='wave_direction',
        ),
    ]
