# Generated by Django 5.0 on 2025-08-10 06:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindArchiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField(verbose_name='forecast_time')),
                ('temperature', models.FloatField(help_text='Temperature at 2 meters above ground', verbose_name='temperature')),
                ('ws10', models.FloatField(verbose_name='ws10')),
                ('wind_direction', models.FloatField(verbose_name='wind_direction')),
                ('wg10', models.FloatField(verbose_name='wg10')),
                ('ws50', models.FloatField(verbose_name='ws50')),
                ('wg50', models.FloatField(verbose_name='wg50')),
            ],
            options={
                'verbose_name': 'wind archive',
                'verbose_name_plural': 'wind archives',
            },
        ),
        migrations.CreateModel(
            name='WindForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField(verbose_name='forecast_time')),
                ('temperature', models.FloatField(help_text='Temperature at 2 meters above ground', verbose_name='temperature')),
                ('ws10', models.FloatField(verbose_name='ws10')),
                ('wind_direction', models.FloatField(verbose_name='wind_direction')),
                ('wg10', models.FloatField(verbose_name='wg10')),
                ('ws50', models.FloatField(verbose_name='ws50')),
                ('wg50', models.FloatField(verbose_name='wg50')),
            ],
        ),
        migrations.CreateModel(
            name='WindStationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='location')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'wind station',
                'verbose_name_plural': 'wind stations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['location'], name='windforecas_locatio_b3c4c5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='windstationmodel',
            constraint=models.UniqueConstraint(fields=('location',), name='unique_location'),
        ),
        migrations.AddField(
            model_name='windforecastmodel',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='windforecastapp.windstationmodel', verbose_name='wind station'),
        ),
        migrations.AddField(
            model_name='windarchivemodel',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='windforecastapp.windstationmodel', verbose_name='wind station'),
        ),
        migrations.AddIndex(
            model_name='windforecastmodel',
            index=models.Index(fields=['forecast_time', 'station'], name='windforecas_forecas_8b60a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='windforecastmodel',
            unique_together={('station', 'forecast_time')},
        ),
        migrations.AddIndex(
            model_name='windarchivemodel',
            index=models.Index(fields=['forecast_time', 'station'], name='windforecas_forecas_de314a_idx'),
        ),
        migrations.AddIndex(
            model_name='windarchivemodel',
            index=models.Index(fields=['station'], name='windforecas_station_ad63bb_idx'),
        ),
    ]
