# Generated by Django 5.0 on 2025-08-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windforecastapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='windstationmodel',
            new_name='location_gist_idx',
            old_name='windforecas_locatio_b3c4c5_idx',
        ),
        migrations.AddIndex(
            model_name='windarchivemodel',
            index=models.Index(fields=['forecast_time'], name='windforecas_forecas_ba1aee_idx'),
        ),
    ]
