# Generated by Django 5.0 on 2025-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windforecastapp', '0002_rename_windforecas_locatio_b3c4c5_idx_location_gist_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windarchivemodel',
            name='wind_direction',
            field=models.PositiveIntegerField(verbose_name='wind_direction'),
        ),
    ]
